platform :ios, '10.0'
use_frameworks!

target 'SygicUIKit_Example' do
    
  pod 'RxSwift', '~>4.1.0'
  pod 'RxCocoa', '~>4.1.0'
  pod 'SygicUIKit', :path => '../'

  target 'SygicUIKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
