use_frameworks!

target 'SygicUIKit_Example' do
  pod 'SygicUIKit', :path => '../'

  target 'SygicUIKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
