# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: objective-c
# cache: cocoapods
podfile: Example/Podfile

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

jobs:
    stage: lint
    script: pod lib lint --allow-warnings
    stage: test
    script: echo "testujeme spolu"

#stages:
#    - name: lint
#    if: branch = master OR breanch =~ ^\d+\.\d+\.\d+$
#    - name: compile
#    if: branch = master OR breanch =~ ^\d+\.\d+\.\d+$
#    - name: test
#    if: branch = master OR breanch =~ ^\d+\.\d+\.\d+$
#    - name: deploy
#    if: breanch =~ ^\d+\.\d+\.\d+$
#    
#script:
#- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SygicUIKit.xcworkspace -scheme SygicUIKit-Example -sdk iphonesimulator12.1 ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint --allow-warnings

