# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: objective-c
#xcode_project: Example/SygicUIKit.xcodeproj
#xcode_scheme: SygicUIKit-Example
#xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
# cache: cocoapods
podfile: Example/Podfile

if: type == pull_request OR (type == push AND branch =~ /^release\/.*$/)

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example # --repo-update

#stages:
#  - name: lint
##    if: branch =~ ^\d+\.\d+\.\d+$
#  - name: test
##    if: branch = master OR breanch =~ ^\d+\.\d+\.\d+$
#  - name: deploy
##    if: branch =~ ^\d+\.\d+\.\d+$
#
#jobs:
#  include:
#    - stage: lint
#      script: pod lib lint --allow-warnings
#    - stage: test
#      script: set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SygicUIKit.xcworkspace -scheme SygicUIKit-Example -sdk iphonesimulator12.1 ONLY_ACTIVE_ARCH=NO | xcpretty
#    - stage: deploy
#      script: echo 'deploing job done'
#      on:
#        tags: true

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SygicUIKit.xcworkspace -scheme SygicUIKit-Example -sdk iphonesimulator12.1 ONLY_ACTIVE_ARCH=YES | xcpretty
- pod lib lint --allow-warnings

deploy:
  provider: script
  script: echo 'deploying log DONE'
  on:
    tag: true
    