osx_image: xcode10.1
language: objective-c
# cache: cocoapods
podfile: Example/Podfile

if: type == pull_request OR (type == push AND branch =~ /^release\/.*$/)

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example # --repo-update

stages:
- name: test
- name: deploy
  if: tag =~ ^\d+\.\d+\.\d+$

jobs:
  include:
    - stage: test
      script: set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SygicUIKit.xcworkspace -scheme SygicUIKit-Example -sdk iphonesimulator12.1 -destination 'platform=iOS Simulator,name=iPhone X,OS=12.1' ONLY_ACTIVE_ARCH=NO | xcpretty
    - script: pod lib lint
    - stage: deploy
      script: pod spec lint
      deploy:
        provider: script
        script: echo "spusteny deploy" #pod trunk push SygicUIKit.podspec
        on:
          tags: true
    