# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: objective-c
# cache: cocoapods
podfile: Example/Podfile

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

#stages:
#  - name: lint
##    if: branch =~ ^\d+\.\d+\.\d+$
#  - name: test
##    if: branch = master OR breanch =~ ^\d+\.\d+\.\d+$
#  - name: deploy
##    if: branch =~ ^\d+\.\d+\.\d+$
#
#jobs:
#  include:
#    - stage: lint
#      script: pod lib lint --allow-warnings
#    - stage: test
#      script: set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SygicUIKit.xcworkspace -scheme SygicUIKit-Example -sdk iphonesimulator12.1 ONLY_ACTIVE_ARCH=NO | xcpretty
#    - stage: deploy
#      script: echo 'deploing job done'
#      on:
#        tags: true

- pod lib lint --allow-warnings
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SygicUIKit.xcworkspace -scheme SygicUIKit-Example -sdk iphonesimulator12.1 ONLY_ACTIVE_ARCH=NO | xcpretty

deploy:
  provider: script
  script: echo 'deploying log DONE'